name = "JacobiEigen"
uuid = "f8d6750e-133d-4ddb-bd4e-1effe2381a20"
authors = ["Zhengbo Zhou", "Marcus Webb"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
